### ISSUE TITLE
DataAnnotations attributes on c# Properties

### ISSUE THREAD

**Issue by larsul** [skbkontur/TypeScript.ContractGenerator#51]
When i'm using data annotations (attributes as Display and MaxLength) on properties in my C# classes, I get an exception about some get_autogeneratedfield is null.

I cannot figure out how to either ignore attributes on that property og completly disable attributes in typescript generation.
Call stack:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: The AutoGenerateField property has not been set.  Use the GetAutoGenerateField method to get the value.
   at System.ComponentModel.DataAnnotations.DisplayAttribute.get_AutoGenerateField()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at SkbKontur.TypeScript.ContractGenerator.Internals.AttributeWrapper.GetValue(MemberInfo memberInfo, Object attribute)
   at SkbKontur.TypeScript.ContractGenerator.Internals.AttributeWrapper.<>c__DisplayClass0_0.<.ctor>b__2(MemberInfo x)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at SkbKontur.TypeScript.ContractGenerator.Internals.AttributeWrapper..ctor(Object attribute)
   at SkbKontur.TypeScript.ContractGenerator.Internals.TypeInfoHelpers.<>c.<GetAttributes>b__0_0(Object x)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at SkbKontur.TypeScript.ContractGenerator.Internals.TypeInfoHelpers.GetAttributes(ICustomAttributeProvider attributeProvider, Boolean inherit)
   at SkbKontur.TypeScript.ContractGenerator.Internals.PropertyWrapper.GetAttributes(Boolean inherit)
   at SkbKontur.TypeScript.ContractGenerator.Extensions.AttributeProviderExtensions.IsNameDefined(IAttributeProvider attributeProvider, String name)
   at SkbKontur.TypeScript.ContractGenerator.TypeScriptGenerator.ResolveProperty(TypeScriptUnit unit, ITypeInfo typeInfo, IPropertyInfo propertyInfo)
   at SkbKontur.TypeScript.ContractGenerator.TypeBuilders.CustomTypeTypeBuildingContext.<>c__DisplayClass6_0.<CreateComplexTypeScriptDefinition>b__0(IPropertyInfo x)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at SkbKontur.TypeScript.ContractGenerator.TypeBuilders.CustomTypeTypeBuildingContext.CreateComplexTypeScriptDefinition(ITypeGenerator typeGenerator)
   at SkbKontur.TypeScript.ContractGenerator.TypeBuilders.CustomTypeTypeBuildingContext.BuildDefinition(ITypeGenerator typeGenerator)
   at SkbKontur.TypeScript.ContractGenerator.TypeScriptGenerator.BuildAllDefinitions()
   at SkbKontur.TypeScript.ContractGenerator.TypeScriptGenerator.Generate()

**Comment by fakefeik** [comment]
Hi

It would be helpful to have a small project with repro of this issue. Could you create one?

**Comment by larsul** [comment]
Ofcourse, sorry... i'll be generating and example today or tomorrow :)

**Comment by larsul** [comment]
Hi,
I created a repository with the code which throw the exception mentioned above.
I cannot see how to either disable attributes for generation or why it's failing.. looked like a problem with properties on attributes not set, but could't figure it completly :(

https://github.com/larsul/TS.Example.Skbkontur

**Comment by fakefeik** [comment]
fixed it in new version

**Comment by larsul** [comment]
Thanks! :)
